//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 02:12:54 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "itmo.com/wst", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.itmo.wst.wsdl;
