//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 11:49:24 PM MSK 
//


package com.itmo.wst.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sugar.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sugar"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="dry"/&gt;
 *     &lt;enumeration value="semi-dry"/&gt;
 *     &lt;enumeration value="semi-sweet"/&gt;
 *     &lt;enumeration value="sweet"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "sugar")
@XmlEnum
public enum Sugar {

    @XmlEnumValue("dry")
    dry("dry"),
    @XmlEnumValue("semi_dry")
    semi_dry("semi_dry"),
    @XmlEnumValue("semi_sweet")
    semi_sweet("semi_sweet"),
    @XmlEnumValue("sweet")
    sweet("sweet");
    private final String value;

    Sugar(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Sugar fromValue(String v) {
        for (Sugar c: Sugar.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
