//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 11:49:24 PM MSK
//


package com.itmo.wst.model;

import java.math.BigInteger;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wine complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="wine"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sugar" type="{itmo.com/wst}sugar" minOccurs="0"/&gt;
 *         &lt;element name="color" type="{itmo.com/wst}color" minOccurs="0"/&gt;
 *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wine", propOrder = {
        "id",
        "name",
        "sugar",
        "color",
        "rating"
})
@Entity
public class Wine {

    @Id
    @XmlElement(required = true)
    protected BigInteger id;
    protected String name;
    @Enumerated(EnumType.STRING)
    @XmlSchemaType(name = "string")
    protected Sugar sugar;
    @XmlSchemaType(name = "string")
    @Enumerated(EnumType.STRING)
    protected Color color;
    protected Float rating;

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sugar property.
     *
     * @return
     *     possible object is
     *     {@link Sugar }
     *
     */
    public Sugar getSugar() {
        return sugar;
    }

    /**
     * Sets the value of the sugar property.
     *
     * @param value
     *     allowed object is
     *     {@link Sugar }
     *
     */
    public void setSugar(Sugar value) {
        this.sugar = value;
    }

    /**
     * Gets the value of the color property.
     *
     * @return
     *     possible object is
     *     {@link Color }
     *
     */
    public Color getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     *
     * @param value
     *     allowed object is
     *     {@link Color }
     *
     */
    public void setColor(Color value) {
        this.color = value;
    }

    /**
     * Gets the value of the rating property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setRating(Float value) {
        this.rating = value;
    }

}
